### ISSUE TITLE
Windows Instructions

### ISSUE THREAD

**Issue by Tobe2d** [XingangPan/DragGAN#34]
Could you share how to get it working on Windows please?

**Comment by nikolaiusa** [comment]
+1

**Comment by Johnandandy** [comment]
+1

**Comment by albusdemens** [comment]
1. Install WSL 2
2. Install Conda on WSL 2
3. Clone the repo and follow the instructions
4. If necessary, check [this suggestion](https://github.com/NVlabs/stylegan3/issues/66#issuecomment-1006375618)

**Comment by waltb01** [comment]
You need to turn on Developer Mode (from Windows Settings) and then from the Add Programs panel, add the "Windows Subsystem for Linux" feature to the Windows OS, as described in this video:
https://www.youtube.com/watch?v=06E5etw4sqk&t=200s

**Comment by PeakGymnast** [comment]
i runned this few minutes ago, and you need to install tons of modules before running GUI successfully on WSL2. Unfortunately, i gave it up

**Comment by Absinthze** [comment]
I can't get it to work on Windows.
I've installed Ubuntu
Conda on Ubuntu
Pytorch

Error: ModuleNotFoundError: No module named 'imgui'

**Comment by raiden2012** [comment]
Can successfully run on anaconda of windows 10. No WSL is needed. 
Quick tips: Install CUDA11.8, VisualStudio, torch with cuda enabled; correctly set `CUDA_HOME` and make sure `_find_compiler_bindir()` can find right MSVC dir.

**Comment by justinjohn0306** [comment]
https://github.com/XingangPan/DragGAN/assets/34035011/03ad7db6-d641-4932-ab72-0e762ab31cb0

**Comment by MattJeanes** [comment]
I was able to get it to run on Windows 11 with miniconda installed and editing the environment.yml file to the following:

```yaml
name: draggan
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python >= 3.8
  - pip
  - numpy>=1.20
  - click>=8.0
  - pillow=9.0.0
  - scipy=1.7.1
  - pytorch=1.9.1
  - torchvision=0.10.1
  - cudatoolkit=11.1
  - requests=2.26.0
  - tqdm=4.62.2
  - ninja=1.10.2
  - matplotlib=3.4.2
  - imageio=2.9.0
  - pip:
    - imgui==1.3.0
    - glfw==2.2.0
    - pyopengl==3.1.5
    - imageio-ffmpeg==0.4.3
    - pyspng
```
Then simply `conda env create -f environment.yml`, `conda activate draggan` and `python .\visualizer_drag.py .\checkpoints\stylegan2-ffhq-512x512.pkl`

I also made a slight tweak to `torch_utils\custom_ops.py` to add support for Visual Studio Preview editions by adding `       C:/Program Files*/Microsoft Visual Studio/*/Preview/VC/Tools/MSVC/*/bin/Hostx64/x64` to the patterns array

![image](https://github.com/XingangPan/DragGAN/assets/2363642/ebb65e38-31de-4622-b5fd-74cb9de8acd8)
