### ISSUE TITLE
ResolvePackageNotFound cudatoolkit=11.1

### ISSUE THREAD

**Issue by Diletant-001** [XingangPan/DragGAN#62]
![image](https://github.com/XingangPan/DragGAN/assets/77320653/e1f677ec-3822-4398-88e9-8e263fd957d6)
And i installed CUDA 11.1
![image](https://github.com/XingangPan/DragGAN/assets/77320653/9280d479-457b-4298-8f7d-5173b768b123)

**Comment by PDillis** [comment]
`11.3.1` works for me (Windows 10), perhaps change the respective package?

For reference, this is the full environment file I use:

```yml
name: stylegan3
channels:
  - pytorch
  - nvidia
  - conda-forge  # PR #80 by @SetZero / #143 by @coldwaterq
dependencies:
  - python >= 3.8
  - pip
  - numpy>=1.20
  - click>=8.0
  - pillow=8.3.1
  - scipy=1.7.1
  - pytorch::pytorch=1.11  # We can now use Pytorch 1.11!
  - cudatoolkit=11.3.1  # Necessary to remove previous PR by @edstoica
  - requests=2.26.0
  - tqdm=4.62.2
  - ninja=1.10.2
  - matplotlib=3.4.2
  - imageio=2.9.0
  - pip:
    - imgui==1.3.0
    - glfw==2.2.0
    - pyopengl==3.1.5
    - imageio-ffmpeg==0.4.3
    - pyspng
    - pyperlin  # for Discriminator Synthesis
    - psutil  # PR #125 by @fastflair / #111 by @siddharthksah
    - tensorboard  # PR #125 by @fastflair
    - torchvision==0.12.0  # For "Discriminator Synthesis" / discriminator_synthesis.py
    - scikit-learn  # For "Self-Distilled StyleGAN" / multimodal_truncation.py
    - opencv-python  # For live visualreactive demo
    - imutils  # Ibidem
    - moviepy==1.0.3
    - ffmpeg-python==0.2.0
    - scikit-video==1.1.11
    - setuptools==59.5.0   # PR #8 by @ZibbeZabbe
```
